version: '3.8'

services:
  sqlDB:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "favordayDB"
    ports:
      - "5432:5432"
    volumes:
      - psql_db:/data/db
  nosqlDB:
    image: mongodb/mongodb-community-server
    container_name: "mongodb"
    ports:
      - "27017:27017"
  web:
    image: favorday-container:latest
    environment:
      DB_HOST: "sqlDB"
      DB_PORT: "5432"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "root"
      DB_NAME: "favordayDB"
      MONGO_HOST: "nosqlDB"
      MONGO_PORT: "27017"
      MONGO_PASSWORD: "root"
      MONGO_DB: "favordayDB"
    ports:
      - "7777:7777"
    depends_on:
      - sqlDB
      - nosqlDB

volumes:
  psql_db: